### ISSUE TITLE
README is probably too long 

### ISSUE THREAD

**Issue by sesam** [Terreii/hoodie-plugin-store-crypto#67]
**Is your feature request related to a problem? Please describe.**
The README.md has a lot of good stuff, but it's so long I can't get a grip on it all.

**Describe the solution you'd like**
Maybe not all of it needs to be in one file?

**Describe alternatives you've considered**
Maybe add a clickable table of contents near the top, so it can be found on first scroll.
Another option could be to extract and move some really long sections to the end of the README, and finish off the readme with a link back to the table of contents.

**Additional context**
Goal should be to capture visitor's attention and quickly show what this plugin does, and make sure the visitor wants to come back again.

**Comment by Terreii** [comment]
👍

Thank you for your feature request (and using my package)!

Absolutely! It just grow and grow!
Much of it could be moved into `docs/`. And leave in the README:
- Small intro (+ thanks)
- This is what it does.
- This is what you need to do.
- Links to:
  - API file
  - Update path (what you need to change from version to version)
  - File explaining the cryptography.

**Comment by Terreii** [comment]
I would be ready to release the updated documentation.

Could you look over it? Thanks.
